name: 'Omar Gate'
description: 'AI-powered security gate that blocks P0/P1 vulnerabilities before merge'
author: 'Sentinelayer'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  # Required
  openai_api_key:
    description: 'OpenAI API key for LLM calls (BYO)'
    required: false
    default: ''

  llm_provider:
    description: 'LLM provider: openai, anthropic, google, xai'
    required: false
    default: 'openai'

  anthropic_api_key:
    description: 'Anthropic API key (required if llm_provider=anthropic)'
    required: false
    default: ''

  google_api_key:
    description: 'Google AI API key (required if llm_provider=google)'
    required: false
    default: ''

  xai_api_key:
    description: 'xAI API key (required if llm_provider=xai)'
    required: false
    default: ''

  # GitHub integration (recommended)
  github_token:
    description: 'GitHub token for posting check runs and comments (use github.token)'
    required: false
    default: ''

  # Sentinelayer integration (optional)
  sentinelayer_token:
    description: 'Sentinelayer API token for Tier 2/3 uploads (optional)'
    required: false
    default: ''

  sentinelayer_spec_id:
    description: 'Sentinelayer spec hash for spec-aware reviews. Generated by sentinelayer.com spec builder.'
    required: false
    default: ''

  sentinelayer_managed_llm:
    description: 'Use Sentinelayer-managed LLM proxy (free-trial mode). If false, auto-enabled when openai_api_key is empty and sentinelayer_token is set.'
    required: false
    default: 'false'

  telemetry_tier:
    description: 'Telemetry tier: 0=off, 1=aggregate, 2=metadata, 3=full artifacts'
    required: false
    default: '1'

  telemetry:
    description: 'Enable anonymous telemetry (opt-out). true/false'
    required: false
    default: 'true'

  share_metadata:
    description: 'Opt-in to Tier 2 metadata (repo identity + finding metadata). true/false'
    required: false
    default: 'false'

  share_artifacts:
    description: 'Opt-in to Tier 3 artifacts upload. true/false'
    required: false
    default: 'false'

  training_opt_in:
    description: 'Optional training consent (de-identified). true/false'
    required: false
    default: 'false'

  # Scan configuration
  scan_mode:
    description: 'Scan mode: pr-diff (fast), deep (full repo), nightly (alias of deep for scheduled runs)'
    required: false
    default: 'pr-diff'

  severity_gate:
    description: 'Minimum severity to block merge: P0, P1, P2, or none'
    required: false
    default: 'P1'

  model:
    description: 'LLM API model (used when Codex CLI is unavailable). Default is gpt-5.2-codex.'
    required: false
    default: 'gpt-5.2-codex'

  model_fallback:
    description: 'Fallback LLM API model (if primary model fails or quota exceeded)'
    required: false
    default: 'gpt-4.1-mini'

  llm_failure_policy:
    description: 'If LLM call fails: block (fail-closed), deterministic_only, allow_with_warning'
    required: false
    default: 'block'

  use_codex:
    description: 'Use Codex CLI for deep agentic audit (falls back to API)'
    required: false
    default: 'true'

  codex_only:
    description: 'Use Codex CLI as the only LLM path (disable API fallback)'
    required: false
    default: 'false'

  codex_model:
    description: 'Model for Codex CLI'
    required: false
    default: 'gpt-5.2-codex'

  codex_timeout:
    description: 'Timeout in seconds for Codex execution'
    required: false
    default: '300'

  run_harness:
    description: 'Run SentinelLayer portable security test harness'
    required: false
    default: 'true'

  # Rate limiting / cost control
  max_daily_scans:
    description: 'Maximum scans per repo per day (0 = unlimited)'
    required: false
    default: '20'

  min_scan_interval_minutes:
    description: 'Minimum minutes between scans for same PR (0 to disable)'
    required: false
    default: '0'

  rate_limit_fail_mode:
    description: "On GitHub API errors during rate limit enforcement: 'closed' (require approval) or 'open' (skip enforcement and proceed)"
    required: false
    default: 'closed'

  max_input_tokens:
    description: 'Maximum input tokens per scan (cost control)'
    required: false
    default: '100000'

  require_cost_confirmation:
    description: 'If estimated cost > $X, require manual confirmation (USD)'
    required: false
    default: '5.00'

  approval_mode:
    description: 'How to approve high-cost scans: pr_label, workflow_dispatch, or none'
    required: false
    default: 'pr_label'

  approval_label:
    description: 'PR label that approves high-cost scan'
    required: false
    default: 'sentinelayer:approved'

  # Fork handling
  fork_policy:
    description: 'Fork PR handling: block, limited (deterministic only), allow'
    required: false
    default: 'block'

  # Fixer options
  run_deterministic_fix:
    description: 'Run deterministic autofix (self-contained allowlist)'
    required: false
    default: 'false'

  run_llm_fix:
    description: 'Generate LLM fix patches (artifacts only, no auto-commit)'
    required: false
    default: 'false'

  auto_commit_fixes:
    description: 'Auto-commit deterministic fixes to PR branch'
    required: false
    default: 'false'

  # Policy pack controls
  policy_pack:
    description: 'Policy pack identifier'
    required: false
    default: 'omar'

  policy_pack_version:
    description: 'Policy pack version'
    required: false
    default: 'v1'

outputs:
  gate_status:
    description: 'Gate result: passed, blocked, bypassed, error'
  p0_count:
    description: 'Number of P0 findings'
  p1_count:
    description: 'Number of P1 findings'
  p2_count:
    description: 'Number of P2 findings'
  p3_count:
    description: 'Number of P3 findings'
  run_id:
    description: 'Unique run identifier'
  findings_artifact:
    description: 'Path to findings JSONL artifact'
  pack_summary_artifact:
    description: 'Path to PACK_SUMMARY.json'
  ingest_artifact:
    description: 'Path to INGEST.json (full ingest payload)'
  codebase_ingest_artifact:
    description: 'Path to CODEBASE_INGEST.json (alias of INGEST.json)'
  codebase_ingest_summary_artifact:
    description: 'Path to CODEBASE_INGEST_SUMMARY.json (codebase snapshot)'
  codebase_ingest_summary_md_artifact:
    description: 'Path to CODEBASE_INGEST_SUMMARY.md (human-readable snapshot)'
  review_brief_artifact:
    description: 'Path to REVIEW_BRIEF.md'
  audit_report_artifact:
    description: 'Path to AUDIT_REPORT.md'
  estimated_cost_usd:
    description: 'Estimated LLM cost for this run'
  idempotency_key:
    description: 'Idempotency key used for dedupe'
  scan_mode:
    description: 'Configured scan mode for this run'
  severity_gate:
    description: 'Configured severity gate threshold for this run'
  llm_provider:
    description: 'Configured LLM provider for this run'
  model:
    description: 'Configured primary LLM model for this run'
  model_fallback:
    description: 'Configured fallback LLM model for this run'
  model_fallback_used:
    description: 'Whether fallback model was used during this run'
  policy_pack:
    description: 'Configured policy pack id for this run'
  policy_pack_version:
    description: 'Configured policy pack version for this run'

runs:
  using: 'docker'
  image: 'Dockerfile'
