name: 'Omar Gate'
description: 'AI-powered security gate that blocks P0/P1 vulnerabilities before merge'
author: 'Sentinelayer'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  # Required
  openai_api_key:
    description: 'OpenAI API key for LLM calls (BYO)'
    required: false
    default: ''

  llm_provider:
    description: 'LLM provider: openai, anthropic, google, xai'
    required: false
    default: 'openai'

  anthropic_api_key:
    description: 'Anthropic API key (required if llm_provider=anthropic)'
    required: false
    default: ''

  google_api_key:
    description: 'Google AI API key (required if llm_provider=google)'
    required: false
    default: ''

  xai_api_key:
    description: 'xAI API key (required if llm_provider=xai)'
    required: false
    default: ''

  # GitHub integration (recommended)
  github_token:
    description: 'GitHub token for posting check runs and comments (use github.token)'
    required: false
    default: ''

  # Sentinelayer integration (optional)
  sentinelayer_token:
    description: 'Sentinelayer API token for Tier 2/3 uploads (optional)'
    required: false
    default: ''

  telemetry_tier:
    description: 'Telemetry tier: 0=off, 1=aggregate, 2=metadata, 3=full artifacts'
    required: false
    default: '1'

  telemetry:
    description: 'Enable anonymous telemetry (opt-out). true/false'
    required: false
    default: 'true'

  share_metadata:
    description: 'Opt-in to Tier 2 metadata (repo identity + finding metadata). true/false'
    required: false
    default: 'false'

  share_artifacts:
    description: 'Opt-in to Tier 3 artifacts upload. true/false'
    required: false
    default: 'false'

  training_opt_in:
    description: 'Optional training consent (de-identified). true/false'
    required: false
    default: 'false'

  # Scan configuration
  scan_mode:
    description: 'Scan mode: pr-diff (fast), deep (full repo), nightly (scheduled)'
    required: false
    default: 'pr-diff'

  severity_gate:
    description: 'Minimum severity to block merge: P0, P1, P2, or none'
    required: false
    default: 'P1'

  model:
    description: 'Primary OpenAI model'
    required: false
    default: 'gpt-5.2-codex'  # TODO: bump to gpt-5.3-codex when available via API

  model_fallback:
    description: 'Fallback OpenAI model'
    required: false
    default: 'gpt-4.1'

  llm_failure_policy:
    description: 'If LLM call fails: block (fail-closed), deterministic_only, allow_with_warning'
    required: false
    default: 'block'

  use_codex:
    description: 'Use Codex CLI for deep agentic audit'
    required: false
    default: 'false'

  codex_model:
    description: 'Model for Codex CLI'
    required: false
    default: 'gpt-5.2-codex'

  codex_timeout:
    description: 'Timeout in seconds for Codex execution'
    required: false
    default: '300'

  run_harness:
    description: 'Run SentinelLayer portable security test harness'
    required: false
    default: 'true'

  # Rate limiting / cost control
  max_daily_scans:
    description: 'Maximum scans per repo per day (0 = unlimited)'
    required: false
    default: '20'

  min_scan_interval_minutes:
    description: 'Minimum minutes between scans for same PR'
    required: false
    default: '5'

  rate_limit_fail_mode:
    description: "On GitHub API errors during rate limit enforcement: 'closed' (require approval) or 'open' (skip enforcement and proceed)"
    required: false
    default: 'closed'

  max_input_tokens:
    description: 'Maximum input tokens per scan (cost control)'
    required: false
    default: '100000'

  require_cost_confirmation:
    description: 'If estimated cost > $X, require manual confirmation (USD)'
    required: false
    default: '5.00'

  approval_mode:
    description: 'How to approve high-cost scans: pr_label, workflow_dispatch, or none'
    required: false
    default: 'pr_label'

  approval_label:
    description: 'PR label that approves high-cost scan'
    required: false
    default: 'sentinelayer:approved'

  # Fork handling
  fork_policy:
    description: 'Fork PR handling: block, limited (deterministic only), allow'
    required: false
    default: 'block'

  # Fixer options
  run_deterministic_fix:
    description: 'Run deterministic autofix (self-contained allowlist)'
    required: false
    default: 'false'

  run_llm_fix:
    description: 'Generate LLM fix patches (artifacts only, no auto-commit)'
    required: false
    default: 'false'

  auto_commit_fixes:
    description: 'Auto-commit deterministic fixes to PR branch'
    required: false
    default: 'false'

  # Policy pack controls
  policy_pack:
    description: 'Policy pack identifier'
    required: false
    default: 'omar'

  policy_pack_version:
    description: 'Policy pack version'
    required: false
    default: 'v1'

outputs:
  gate_status:
    description: 'Gate result: passed, blocked, bypassed, error'
  p0_count:
    description: 'Number of P0 findings'
  p1_count:
    description: 'Number of P1 findings'
  p2_count:
    description: 'Number of P2 findings'
  p3_count:
    description: 'Number of P3 findings'
  run_id:
    description: 'Unique run identifier'
  findings_artifact:
    description: 'Path to findings JSONL artifact'
  pack_summary_artifact:
    description: 'Path to PACK_SUMMARY.json'
  estimated_cost_usd:
    description: 'Estimated LLM cost for this run'
  idempotency_key:
    description: 'Idempotency key used for dedupe'

runs:
  using: 'docker'
  image: 'Dockerfile'
