name: Deploy sentinelayer-api to ECS

on:
  push:
    branches: [ "main" ]
    paths:
      - "sentinelayer-api/**"
      - ".github/workflows/deploy-api.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sentinelayer-prod-api # update to Terraform output (name, not URL)
  TF_WORKING_DIR: sentinellayer-aws-terraform-v0.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_project_name: ${{ vars.TF_PROJECT_NAME || 'sentinelayer' }}
      TF_VAR_environment: ${{ vars.TF_ENVIRONMENT || 'prod' }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION || 'us-east-1' }}
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_route53_zone_id: ${{ vars.ROUTE53_ZONE_ID }}
      TF_VAR_api_runtime_secret_arn: ${{ vars.API_RUNTIME_SECRET_ARN }}
      # IMPORTANT: Set these to match your baseline so CI deploys don't revert sizing to Terraform defaults.
      TF_VAR_api_container_port: ${{ vars.API_CONTAINER_PORT || '8000' }}
      TF_VAR_desired_count: ${{ vars.DESIRED_COUNT || '2' }}
      TF_VAR_max_count: ${{ vars.MAX_COUNT || '20' }}
      TF_VAR_api_cpu: ${{ vars.API_CPU || '512' }}
      TF_VAR_api_memory: ${{ vars.API_MEMORY || '1024' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        id: build-image
        working-directory: sentinelayer-api
        run: |
          IMAGE_TAG=${GITHUB_SHA::12}
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${IMAGE_TAG}"

          docker build -t "${IMAGE_URI}" -f Dockerfile .
          docker push "${IMAGE_URI}"

          echo "image_uri=${IMAGE_URI}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_KEY || 'sentinelayer/prod/terraform.tfstate' }}" \
            -backend-config="region=${{ vars.AWS_REGION || 'us-east-1' }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform apply image update
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
            -var="api_image_tag=${{ steps.build-image.outputs.image_tag }}"

      - name: Post-deploy smoke check
        run: |
          DOMAIN="${TF_VAR_domain_name:-sentinelayer.com}"
          curl -fsS --retry 5 --retry-delay 10 "https://api.${DOMAIN}/health"
