name: Terraform Drift Check (refresh-only)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 7 * * 1-5" # Weekdays 07:15 UTC

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  TF_WORKING_DIR: sentinellayer-aws-terraform-v0.1

jobs:
  drift-check:
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_project_name: ${{ vars.TF_PROJECT_NAME || 'sentinelayer' }}
      TF_VAR_environment: ${{ vars.TF_ENVIRONMENT || 'prod' }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION || 'us-east-1' }}
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_route53_zone_id: ${{ vars.ROUTE53_ZONE_ID }}
      TF_VAR_api_runtime_secret_arn: ${{ vars.API_RUNTIME_SECRET_ARN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_READONLY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_KEY || 'sentinelayer/prod/terraform.tfstate' }}" \
            -backend-config="region=${{ vars.AWS_REGION || 'us-east-1' }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform plan -refresh-only
        id: drift
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          set +e
          terraform plan -refresh-only -detailed-exitcode -no-color -out=drift.tfplan
          exit_code=$?
          set -e
          echo "exit_code=${exit_code}" >> "$GITHUB_OUTPUT"
          terraform show -no-color drift.tfplan > drift.txt || true
          if [ "$exit_code" -eq 1 ]; then
            echo "Terraform refresh-only plan failed"
            exit 1
          fi

      - name: Upload drift artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-drift-report
          path: |
            ${{ env.TF_WORKING_DIR }}/drift.txt
            ${{ env.TF_WORKING_DIR }}/drift.tfplan

      - name: Fail on detected drift
        if: steps.drift.outputs.exit_code == '2'
        run: |
          echo "Drift detected. Human approval + change record required."
          exit 1
